import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

function readableBuildTimestamp(date = new Date()) {
	return date.toLocaleString("en-US", {
		weekday: "short",
		month: "short",
		day: "numeric",
		year: "numeric",
		hour: "numeric",
		minute: "2-digit",
		second: "2-digit",
		hour12: true,
		timeZoneName: "short",
	});
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Build timestamp: ${readableBuildTimestamp()}
if you want to view the source, please visit the plugin repository
*/
`;

const mode = process.argv[2];
const prod = mode === "production";
const preview = mode === "preview";

const pluginBuild = {
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
};

const previewBuild = {
	entryPoints: ["preview/preview.ts"],
	bundle: true,
	format: "iife",
	target: "es2021",
	logLevel: "info",
	outfile: "preview/preview.js",
	sourcemap: false,
};

if (preview) {
	await esbuild.build(previewBuild);
	process.exit(0);
}

if (prod) {
	await esbuild.build(pluginBuild);
	await esbuild.build(previewBuild);
	process.exit(0);
}

const context = await esbuild.context(pluginBuild);
await context.watch();
